image: alpine:latest

pages:
  script:
  - rm -r public/* || echo -n ""
  - mkdir -p public
  - find . -maxdepth 1 -not -ipath './.git*' -not -ipath './public*' -not -ipath '.' -exec cp -r '{}' './public/{}' ';'
  artifacts:
    paths:
    - public

